name: flutter_vision_kit
description: A Flutter Plugin to access Apple iOS VisionKit Document Scanner.
version: 0.0.1
homepage: https://github.com/spielgestalt/flutter_vision_kit

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterVisionKitPlugin